/**
 * Dual-Lock Range Sentinel "Create DBot" — end-to-end proof against the REAL builder.
 *
 * The NeuroTrade API renders a Blockly strategy for the scanned Dual-Lock lock
 * (fixtures generated by artifacts/api-server/src/lib/dual-lock-dbot.ts). These
 * tests load that XML into the real Deriv Blockly with every vendored block
 * definition, run the builder's own pre-run validation — crucially the mandatory
 * block gate that raises "The Purchase block is mandatory…" — generate
 * JavaScript exactly the way `dbot.generateCode()` does, and EXECUTE it against a
 * scripted market with a fake `Bot` interface.
 *
 * The difference from the Turbo DBot: this bot carries no in-bot analysis EXCEPT
 * the first-entry timing gate, which runs once per run (and is bounded by its
 * patience budget). After that first purchase it fires the locked normal
 * contract every tick and, on a loss, the locked recovery contract every tick at
 * the shared recovery-ladder stake (debt × 1.1 / (payout − 1), rounded up to
 * cents, back to base on cleared debt, circuit breaker / TP / SL halts) — no
 * arming, no recovery-timing gate.
 */
import fs from 'fs';
import path from 'path';
import { localize } from '@deriv-com/translations';
import { loadBlockly } from '../../external/bot-skeleton/scratch/blockly';
import DBotStore from '../../external/bot-skeleton/scratch/dbot-store';
import { isAllRequiredBlocksEnabled } from '../../external/bot-skeleton/scratch/utils';
import { analyseDualLockEntry } from '../../external/bot-skeleton/services/tradeEngine/trade/dual-lock-entry';

localize.mockImplementation((text, args) =>
    typeof text === 'string' ? text.replace(/{{\s*(\w+)\s*}}/g, (match, key) => (args && key in args ? args[key] : match)) : text
);

const FIXTURES = path.join(__dirname, 'fixtures');
const readFixture = name => fs.readFileSync(path.join(FIXTURES, `${name}.xml`), 'utf8');

// Payouts the fake market pays (total return per 1 staked), matching the seeds
// the API quoted into the fixture so the ladder maths is exactly predictable.
const PAYOUT = { 'DIGITOVER:2': 1.4, 'DIGITOVER:4': 1.95, 'DIGITUNDER:7': 1.4, 'DIGITUNDER:5': 1.95 };

/** Mirror of dbot.generateCode() + the interpreter's main loop, run natively. */
function buildRunner(workspace) {
    window.Blockly.derivWorkspace = workspace;
    const varDB = new window.Blockly.Names('window');
    varDB.variableMap = workspace.getVariableMap();
    window.Blockly.JavaScript.variableDB_ = varDB;

    const generator = window.Blockly.JavaScript.javascriptGenerator;
    generator.init(workspace);
    const body = generator.workspaceToCode(workspace);

    return `
        var BinaryBotPrivateInit;
        var BinaryBotPrivateStart;
        var BinaryBotPrivateBeforePurchase;
        var BinaryBotPrivateDuringPurchase;
        var BinaryBotPrivateAfterPurchase;
        var BinaryBotPrivateLastTickTime;
        var BinaryBotPrivateTickAnalysisList = [];
        var BinaryBotPrivateHasCalledTradeOptions = false;
        function BinaryBotPrivateRun(f, arg) { if (f) return f(arg); return false; }
        function BinaryBotPrivateTickAnalysis() {}
        var BinaryBotPrivateLimitations = {};
        ${body}
        BinaryBotPrivateRun(BinaryBotPrivateInit);
        var guard = 0;
        while (true) {
            if (++guard > 500) throw new Error('runaway trade loop');
            BinaryBotPrivateRun(BinaryBotPrivateStart);
            if (!BinaryBotPrivateHasCalledTradeOptions) { sleep(1); continue; }
            var beforeGuard = 0;
            while (watch('before')) {
                if (++beforeGuard > 200) throw new Error('purchase conditions never purchased');
                BinaryBotPrivateRun(BinaryBotPrivateBeforePurchase);
            }
            while (watch('during')) { BinaryBotPrivateRun(BinaryBotPrivateDuringPurchase); }
            if (!BinaryBotPrivateRun(BinaryBotPrivateAfterPurchase)) break;
        }
    `;
}

/** A tape where every digit satisfies the locked contract (gate opens at once). */
const cleanTape = (contract, barrier, length = 80) =>
    Array.from({ length }, () => (contract === 'DIGITUNDER' ? Math.max(0, barrier - 1) : Math.min(9, barrier + 1)));

/** A tape where every digit violates it (gate holds until its deadline). */
const hostileTape = (contract, barrier, length = 80) =>
    Array.from({ length }, () => (contract === 'DIGITUNDER' ? Math.min(9, barrier + 1) : Math.max(0, barrier - 1)));

/**
 * Scripted Deriv: `results` are the outcomes of successive purchases.
 *
 * `entryTape` feeds the REAL first-entry model (`analyseDualLockEntry`) so these
 * tests exercise the generated wiring against the production maths, not a stub.
 * It may be an array or a function of the evaluation count.
 */
function fakeMarket({ results, balance = 1000, entryTape = null }) {
    const state = {
        trades: [],
        notifications: [],
        totalProfit: 0,
        balance,
        purchased: false,
        tradeOptions: null,
        init: null,
        beforeEvaluations: 0,
        entryCalls: [],
        exhausted: false,
    };
    let entryDecision = null;
    const contract = { buy_price: 0, sell_price: 0, profit: 0, result: 'win' };
    const Bot = {
        init: (account, options) => { state.init = { account, ...options }; },
        start: options => { state.tradeOptions = options; state.purchased = false; },
        highlightBlock: () => {},
        purchase: type => {
            if (state.trades.length >= results.length) { state.exhausted = true; throw new Error('SCRIPT_EXHAUSTED'); }
            const won = results[state.trades.length] === 'W';
            const stake = state.tradeOptions.amount;
            const prediction = state.tradeOptions.prediction;
            const multiplier = PAYOUT[`${type}:${prediction}`];
            if (!multiplier) throw new Error(`unexpected contract ${type} barrier ${prediction}`);
            const sell = won ? Math.round(stake * multiplier * 100) / 100 : 0;
            contract.buy_price = stake;
            contract.sell_price = sell;
            contract.profit = Math.round((sell - stake) * 100) / 100;
            contract.result = won ? 'win' : 'loss';
            state.totalProfit = Math.round((state.totalProfit + contract.profit) * 100) / 100;
            state.balance = Math.round((state.balance + contract.profit) * 100) / 100;
            state.trades.push({ type, prediction, stake, won, profit: contract.profit });
            state.purchased = true;
        },
        isResult: r => contract.result === r,
        readDetails: i => [null, null, contract.buy_price, contract.sell_price, contract.profit][i],
        getTotalProfit: () => state.totalProfit,
        getBalance: () => state.balance,
        notify: n => state.notifications.push(n.message),
        isTradeAgain: () => {},
        getLastTick: () => ({ epoch: Date.now() }),
        ntAnalyseDualLockEntry: (contract, barrier, windowSize, patience, waited) => {
            state.entryCalls.push({ contract, barrier, windowSize, patience, waited });
            const tape = typeof entryTape === 'function' ? entryTape(waited) : entryTape;
            entryDecision = analyseDualLockEntry({
                digits: tape ?? cleanTape(contract, barrier),
                contract,
                barrier,
                waited,
                patience,
            });
            return entryDecision.ready;
        },
        ntDualLockEntryDecision: field =>
            entryDecision ? entryDecision[field] : field === 'reason' ? 'entry timing warming up' : 0,
    };
    const watch = scope => {
        if (scope !== 'before') return false;
        if (state.purchased) return false;
        state.beforeEvaluations += 1;
        return true;
    };
    return { Bot, watch, sleep: () => {}, state };
}

function runStrategy(code, market) {
    // eslint-disable-next-line no-new-func
    const fn = new Function('Bot', 'watch', 'sleep', code);
    try {
        fn(market.Bot, market.watch, market.sleep);
        return 'stopped';
    } catch (error) {
        if (error.message === 'SCRIPT_EXHAUSTED') return 'exhausted';
        if (error.message === 'purchase conditions never purchased') return 'waiting';
        throw error;
    }
}

describe('Dual-Lock Range Sentinel → Deriv DBot strategy', () => {
    let workspace;

    beforeAll(async () => {
        await loadBlockly(false);
        const proto = window.Blockly.Block.prototype;
        for (const method of ['initSvg', 'render', 'renderEfficiently', 'queueRender', 'bumpNeighbours', 'scheduleSnapAndBump', 'markDirty']) {
            if (!proto[method]) proto[method] = () => {};
        }
        DBotStore.setInstance({
            client: { is_logged_in: true, loginid: 'VRTC0000001', currency: 'USD' },
            setLoading: () => {},
            load_modal: { setOpenButtonDisabled: () => {}, setLoadedLocalFile: () => {} },
        });
    }, 120000);

    beforeEach(() => {
        window.Blockly.Events.disable();
        workspace = new window.Blockly.Workspace();
    });

    afterEach(() => {
        workspace.dispose();
        window.Blockly.Events.enable();
    });

    const loadFixture = name => {
        const xml = readFixture(name);
        const dom = window.Blockly.utils.xml.textToDom(xml);
        const block_types = Array.from(dom.querySelectorAll('block')).map(b => b.getAttribute('type'));
        expect(block_types.length).toBeGreaterThan(0);
        const unknown = block_types.filter(type => !Object.keys(window.Blockly.Blocks).includes(type));
        expect(unknown).toEqual([]);
        window.Blockly.Xml.domToWorkspace(dom, workspace);
        return xml;
    };

    it('loads into the real builder with every Deriv root block in place', () => {
        loadFixture('duallock-r100-over2-over4');
        const tops = workspace.getTopBlocks(false).map(b => b.type).sort();
        expect(tops).toEqual(['after_purchase', 'before_purchase', 'procedures_defnoreturn', 'trade_definition']);
        const market = workspace.getBlocksByType('trade_definition_market', false)[0];
        expect(market.getFieldValue('SYMBOL_LIST')).toBe('R_100');
        expect(market.getFieldValue('MARKET_LIST')).toBe('synthetic_index');
        expect(market.getFieldValue('SUBMARKET_LIST')).toBe('random_index');
        expect(workspace.getBlocksByType('trade_definition_tradetype', false)[0].getFieldValue('TRADETYPE_LIST')).toBe('overunder');
        expect(workspace.getBlocksByType('trade_definition_contracttype', false)[0].getFieldValue('TYPE_LIST')).toBe('both');
        const options = workspace.getBlocksByType('trade_definition_tradeoptions', false)[0];
        expect(options.getFieldValue('DURATIONTYPE_LIST')).toBe('t');
        expect(options.getInputTargetBlock('PREDICTION').type).toBe('variables_get');
        expect(options.getInputTargetBlock('AMOUNT').type).toBe('variables_get');
        expect(workspace.getBlocksByType('procedures_defnoreturn', false)).toHaveLength(1);
        expect(workspace.getBlocksByType('procedures_callnoreturn', false).length).toBeGreaterThanOrEqual(2);
    });

    it('passes the run-button gate with a stock purchase block and only the first-entry gate', () => {
        // This is the exact gate that raises "The Purchase block is mandatory…".
        // The Dual-Lock DBot still buys through the stock `purchase` block (the
        // first-entry gate only decides WHEN), so the gate accepts it as before.
        for (const fixture of ['duallock-r100-over2-over4', 'duallock-1hz100v-under7-under5-wide']) {
            workspace.dispose();
            workspace = new window.Blockly.Workspace();
            loadFixture(fixture);
            window.Blockly.derivWorkspace = workspace;
            expect(workspace.getBlocksByType('purchase', false).length).toBeGreaterThanOrEqual(1);
            expect(workspace.getBlocksByType('nt_analyse_dual_lock_entry', false)).toHaveLength(1);
            expect(workspace.getBlocksByType('nt_analyse_turbo_recovery', false)).toHaveLength(0);
            expect(workspace.getBlocksByType('nt_turbo_recovery_decision', false)).toHaveLength(0);
            expect(workspace.getBlocksByType('nt_purchase_contract', false)).toHaveLength(0);
            expect(isAllRequiredBlocksEnabled(workspace)).toBe(true);
        }
    });

    it('fires the lock every tick after the timed start, and recovers with the shared ladder', () => {
        loadFixture('duallock-r100-over2-over4');
        const code = buildRunner(workspace);
        expect(code).toContain("symbol              : 'R_100'");
        expect(code).toContain('Bot.purchase');
        // The only analysis call is the first-entry gate.
        expect(code).toContain('Bot.ntAnalyseDualLockEntry');
        expect(code).not.toContain('Bot.ntAnalyseTurboRecovery');
        expect(code).not.toContain('Bot.getLastDigitList');

        const market = fakeMarket({ results: ['W', 'L', 'L', 'W', 'W'] });
        expect(runStrategy(code, market)).toBe('exhausted');

        expect(market.state.init.symbol).toBe('R_100');
        expect(market.state.tradeOptions.duration).toBe(1);
        expect(market.state.tradeOptions.duration_unit).toBe('t');

        const trades = market.state.trades.map(t => [t.type, t.prediction, t.stake, t.won ? 'W' : 'L']);
        expect(trades).toEqual([
            ['DIGITOVER', 2, 1, 'W'], // normal leg at base stake, fired immediately (no arming)
            ['DIGITOVER', 2, 1, 'L'], // loss → debt 1.00
            ['DIGITOVER', 4, 1.16, 'L'], // recovery: ceil₂(1.00 × 1.1 / 0.95) = 1.16 → debt 2.16
            ['DIGITOVER', 4, 2.51, 'W'], // recovery: ceil₂(2.16 × 1.1 / 0.95) = 2.51 → +2.38 clears debt
            ['DIGITOVER', 2, 1, 'W'], // straight back to the normal leg at base stake
        ]);
        // Timing ran once, for the locked contract only, and never again.
        expect(market.state.entryCalls).toHaveLength(1);
        expect(market.state.entryCalls[0]).toMatchObject({ contract: 'DIGITOVER', barrier: 2, patience: 12, waited: 1 });
        expect(market.state.notifications.some(m => /first entry timed within 12 ticks/.test(m))).toBe(true);
        expect(market.state.notifications.some(m => /Over 2 on Volatility 100 Index — TIMED ENTRY/.test(m))).toBe(true);
        expect(market.state.notifications.some(m => /Recovery step 1 — Over 4 sized at 1.16 USD to clear 1 USD.*firing back-to-back/.test(m))).toBe(true);
        expect(market.state.notifications.some(m => /Recovery complete — debt cleared/.test(m))).toBe(true);
    });

    it('waits for a well-timed first entry instead of firing into a violation burst', () => {
        loadFixture('duallock-r100-over2-over4');
        const code = buildRunner(workspace);
        // The tape is hostile for the first 4 evaluations, then the range holds.
        const market = fakeMarket({
            results: ['W'],
            entryTape: waited => (waited <= 4 ? hostileTape('DIGITOVER', 2) : cleanTape('DIGITOVER', 2)),
        });
        expect(runStrategy(code, market)).toBe('exhausted');

        // Five evaluations: four holds, then the entry — and nothing bought early.
        expect(market.state.entryCalls.map(call => call.waited)).toEqual([1, 2, 3, 4, 5]);
        expect(market.state.trades).toHaveLength(1);
        expect(market.state.trades[0]).toMatchObject({ type: 'DIGITOVER', prediction: 2, stake: 1 });
        expect(market.state.notifications.some(m => /Waiting for a clean start — TIMING 3\/12/.test(m))).toBe(true);
        expect(market.state.notifications.some(m => /TIMED ENTRY · \d+ clean ticks/.test(m))).toBe(true);
        expect(market.state.notifications.some(m => /patience budget reached/.test(m))).toBe(false);
    });

    it('never stalls: a permanently hostile tape still starts at the patience deadline', () => {
        loadFixture('duallock-r100-over2-over4');
        const code = buildRunner(workspace);
        const market = fakeMarket({ results: ['W'], entryTape: hostileTape('DIGITOVER', 2) });
        expect(runStrategy(code, market)).toBe('exhausted');

        // Bounded wait: exactly the 12-tick patience budget, then the locked buy.
        expect(market.state.entryCalls).toHaveLength(12);
        expect(market.state.trades).toHaveLength(1);
        expect(market.state.trades[0]).toMatchObject({ type: 'DIGITOVER', prediction: 2, stake: 1 });
        expect(market.state.notifications.some(m => /patience budget reached/.test(m))).toBe(true);
    });

    it('times only the FIRST entry — every later normal and recovery trade fires straight away', () => {
        loadFixture('duallock-r100-over2-over4');
        const code = buildRunner(workspace);
        const market = fakeMarket({ results: ['L', 'L', 'W', 'W', 'W'] });
        expect(runStrategy(code, market)).toBe('exhausted');

        expect(market.state.trades).toHaveLength(5);
        // One timing call for five trades: the gate latches open after the first.
        expect(market.state.entryCalls).toHaveLength(1);
        expect(market.state.trades.map(t => [t.type, t.prediction, t.stake])).toEqual([
            ['DIGITOVER', 2, 1],
            ['DIGITOVER', 4, 1.16],
            ['DIGITOVER', 4, 2.51],
            ['DIGITOVER', 2, 1],
            ['DIGITOVER', 2, 1],
        ]);
    });

    it('times the Under lock on its own terms (same gate, no per-market tuning)', () => {
        loadFixture('duallock-1hz100v-under7-under5-wide');
        const code = buildRunner(workspace);
        const market = fakeMarket({ results: ['W'] });
        expect(runStrategy(code, market)).toBe('exhausted');

        expect(market.state.entryCalls[0]).toMatchObject({ contract: 'DIGITUNDER', barrier: 7 });
        expect(market.state.trades[0]).toMatchObject({ type: 'DIGITUNDER', prediction: 7 });
    });

    it('stops at stop-loss on a losing ladder and never trades past it', () => {
        loadFixture('duallock-r100-over2-over4');
        const code = buildRunner(workspace);
        const market = fakeMarket({ results: ['L', 'L', 'L', 'L', 'L', 'L', 'L', 'L'] });
        expect(runStrategy(code, market)).toBe('stopped');
        // 1.00 → 1.16 → 2.51 → ceil₂(4.67 × 1.1 / 0.95) = 5.41 ; total −10.08 ≤ −5 → SL halt
        expect(market.state.trades.map(t => t.stake)).toEqual([1, 1.16, 2.51, 5.41]);
        expect(market.state.trades.map(t => t.prediction)).toEqual([2, 4, 4, 4]);
        expect(market.state.totalProfit).toBeLessThanOrEqual(-5);
        expect(market.state.notifications.some(m => /Stop loss 5.00 USD hit/.test(m))).toBe(true);
    });

    it('stops at take-profit', () => {
        loadFixture('duallock-r100-over2-over4');
        const code = buildRunner(workspace);
        const market = fakeMarket({ results: Array.from({ length: 40 }, () => 'W') });
        expect(runStrategy(code, market)).toBe('stopped');
        // 0.40 per win → 25 wins reach the 10.00 take-profit.
        expect(market.state.trades).toHaveLength(25);
        expect(market.state.totalProfit).toBeGreaterThanOrEqual(10);
        expect(market.state.notifications.some(m => /Take profit 10.00 USD reached/.test(m))).toBe(true);
    });

    it('trips the circuit breaker after the modelled loss depth (Under lock, wide TP/SL)', () => {
        loadFixture('duallock-1hz100v-under7-under5-wide');
        const code = buildRunner(workspace);
        expect(code).toContain("symbol              : '1HZ100V'");
        const market = fakeMarket({ results: Array.from({ length: 12 }, () => 'L') });
        expect(runStrategy(code, market)).toBe('stopped');
        // breakerDepth 5 → exactly 5 consecutive losses, then halt.
        expect(market.state.trades).toHaveLength(5);
        expect(market.state.trades.map(t => [t.type, t.prediction])).toEqual([
            ['DIGITUNDER', 7],
            ['DIGITUNDER', 5],
            ['DIGITUNDER', 5],
            ['DIGITUNDER', 5],
            ['DIGITUNDER', 5],
        ]);
        expect(market.state.notifications.some(m => /Circuit breaker: 5 consecutive losses/.test(m))).toBe(true);
    });
});
