/**
 * Over/Under Turbo "Create DBot" — end-to-end proof against the REAL builder.
 *
 * The NeuroTrade API renders a Blockly strategy for the scanned Turbo lock
 * (fixtures generated by artifacts/api-server/src/lib/overunder-turbo-dbot.ts).
 * These tests load that XML into the real Deriv Blockly with every vendored
 * block definition, run the builder's own pre-load validation (the same checks
 * `load()` applies), generate JavaScript exactly the way `dbot.generateCode()`
 * does, and EXECUTE it against a scripted market with a fake `Bot` interface.
 *
 * That last step is what pins the product promise: the DBot must trade the
 * scanned market/barriers and recover with the same ladder as the Turbo engine
 * (debt × 1.1 / (payout − 1), rounded up to cents, back to base on cleared debt,
 * circuit breaker / TP / SL halts).
 */
import fs from 'fs';
import path from 'path';
import { localize } from '@deriv-com/translations';
import { loadBlockly } from '../../external/bot-skeleton/scratch/blockly';
import DBotStore from '../../external/bot-skeleton/scratch/dbot-store';

// Block definitions interpolate `{{ placeholders }}` into Blockly `%N` tokens;
// the package mock returns the raw key, so give it the real substitution here.
localize.mockImplementation((text, args) =>
    typeof text === 'string' ? text.replace(/{{\s*(\w+)\s*}}/g, (match, key) => (args && key in args ? args[key] : match)) : text
);

const FIXTURES = path.join(__dirname, 'fixtures');
const readFixture = name => fs.readFileSync(path.join(FIXTURES, `${name}.xml`), 'utf8');

// Payouts the fake market pays (total return per 1 staked), matching the seeds
// the API quoted into the fixture so the ladder maths is exactly predictable.
const PAYOUT = { 'DIGITOVER:2': 1.4, 'DIGITOVER:4': 1.95, 'DIGITUNDER:7': 1.4, 'DIGITUNDER:5': 1.95 };

const GOOD_DIGITS = Array.from({ length: 60 }, (_, i) => (i % 10 === 0 ? 1 : 5 + (i % 5))); // Over 2 / Under 7 mostly win
const BAD_DIGITS = Array.from({ length: 60 }, () => 0); // Over 2 never wins, Under 7 always wins

/** Mirror of dbot.generateCode() + the interpreter's main loop, run natively. */
function buildRunner(workspace) {
    window.Blockly.derivWorkspace = workspace;
    const varDB = new window.Blockly.Names('window');
    varDB.variableMap = workspace.getVariableMap();
    window.Blockly.JavaScript.variableDB_ = varDB;

    const generator = window.Blockly.JavaScript.javascriptGenerator;
    generator.init(workspace);
    const body = generator.workspaceToCode(workspace);

    // dbot.js:generateCode — private scaffolding + the interpreter's trade loop.
    return `
        var BinaryBotPrivateInit;
        var BinaryBotPrivateStart;
        var BinaryBotPrivateBeforePurchase;
        var BinaryBotPrivateDuringPurchase;
        var BinaryBotPrivateAfterPurchase;
        var BinaryBotPrivateLastTickTime;
        var BinaryBotPrivateTickAnalysisList = [];
        var BinaryBotPrivateHasCalledTradeOptions = false;
        function BinaryBotPrivateRun(f, arg) { if (f) return f(arg); return false; }
        function BinaryBotPrivateTickAnalysis() {}
        var BinaryBotPrivateLimitations = {};
        ${body}
        BinaryBotPrivateRun(BinaryBotPrivateInit);
        var guard = 0;
        while (true) {
            if (++guard > 500) throw new Error('runaway trade loop');
            BinaryBotPrivateRun(BinaryBotPrivateStart);
            if (!BinaryBotPrivateHasCalledTradeOptions) { sleep(1); continue; }
            var beforeGuard = 0;
            while (watch('before')) {
                if (++beforeGuard > 200) throw new Error('purchase conditions never purchased');
                BinaryBotPrivateRun(BinaryBotPrivateBeforePurchase);
            }
            while (watch('during')) { BinaryBotPrivateRun(BinaryBotPrivateDuringPurchase); }
            if (!BinaryBotPrivateRun(BinaryBotPrivateAfterPurchase)) break;
        }
    `;
}

/** Scripted Deriv: `results` are the outcomes of successive purchases. */
function fakeMarket({ results, digits = () => GOOD_DIGITS, balance = 1000 }) {
    const state = {
        trades: [],
        notifications: [],
        totalProfit: 0,
        balance,
        purchased: false,
        tradeOptions: null,
        init: null,
        beforeEvaluations: 0,
        exhausted: false,
    };
    const contract = { buy_price: 0, sell_price: 0, profit: 0, result: 'win' };
    const Bot = {
        init: (account, options) => { state.init = { account, ...options }; },
        start: options => { state.tradeOptions = options; state.purchased = false; },
        highlightBlock: () => {},
        purchase: type => {
            if (state.trades.length >= results.length) { state.exhausted = true; throw new Error('SCRIPT_EXHAUSTED'); }
            const won = results[state.trades.length] === 'W';
            const stake = state.tradeOptions.amount;
            const prediction = state.tradeOptions.prediction;
            const multiplier = PAYOUT[`${type}:${prediction}`];
            if (!multiplier) throw new Error(`unexpected contract ${type} barrier ${prediction}`);
            const sell = won ? Math.round(stake * multiplier * 100) / 100 : 0;
            contract.buy_price = stake;
            contract.sell_price = sell;
            contract.profit = Math.round((sell - stake) * 100) / 100;
            contract.result = won ? 'win' : 'loss';
            state.totalProfit = Math.round((state.totalProfit + contract.profit) * 100) / 100;
            state.balance = Math.round((state.balance + contract.profit) * 100) / 100;
            state.trades.push({ type, prediction, stake, won, profit: contract.profit });
            state.purchased = true;
        },
        isResult: r => contract.result === r,
        readDetails: i => [null, null, contract.buy_price, contract.sell_price, contract.profit][i],
        getTotalProfit: () => state.totalProfit,
        getBalance: () => state.balance,
        getLastDigitList: () => digits(state),
        notify: n => state.notifications.push(n.message),
        isTradeAgain: () => {},
        getLastTick: () => ({ epoch: Date.now() }),
    };
    const watch = scope => {
        if (scope !== 'before') return false;
        if (state.purchased) return false;
        state.beforeEvaluations += 1;
        return true;
    };
    return { Bot, watch, sleep: () => {}, state };
}

function runStrategy(code, market) {
    // eslint-disable-next-line no-new-func
    const fn = new Function('Bot', 'watch', 'sleep', code);
    try {
        fn(market.Bot, market.watch, market.sleep);
        return 'stopped';
    } catch (error) {
        if (error.message === 'SCRIPT_EXHAUSTED') return 'exhausted';
        throw error;
    }
}

describe('Over/Under Turbo → Deriv DBot strategy', () => {
    let workspace;

    beforeAll(async () => {
        await loadBlockly(false);
        // Headless workspace: Deriv's trade-options mutator renders the prediction
        // shadow (initSvg / renderEfficiently exist only on BlockSvg). No-op them
        // so the same code path runs without an SVG canvas.
        const proto = window.Blockly.Block.prototype;
        for (const method of ['initSvg', 'render', 'renderEfficiently', 'queueRender', 'bumpNeighbours', 'scheduleSnapAndBump', 'markDirty']) {
            if (!proto[method]) proto[method] = () => {};
        }
        // trade_definition's generator refuses to run logged-out; mirror a demo login.
        DBotStore.setInstance({
            client: { is_logged_in: true, loginid: 'VRTC0000001', currency: 'USD' },
            setLoading: () => {},
            load_modal: { setOpenButtonDisabled: () => {}, setLoadedLocalFile: () => {} },
        });
    }, 120000);

    beforeEach(() => {
        window.Blockly.Events.disable();
        workspace = new window.Blockly.Workspace();
    });

    afterEach(() => {
        workspace.dispose();
        window.Blockly.Events.enable();
    });

    const loadFixture = name => {
        const xml = readFixture(name);
        const dom = window.Blockly.utils.xml.textToDom(xml);
        // The same gates load() applies before touching the workspace.
        const block_types = Array.from(dom.querySelectorAll('block')).map(b => b.getAttribute('type'));
        expect(block_types.length).toBeGreaterThan(0);
        const unknown = block_types.filter(type => !Object.keys(window.Blockly.Blocks).includes(type));
        expect(unknown).toEqual([]);
        window.Blockly.Xml.domToWorkspace(dom, workspace);
        return xml;
    };

    it('loads into the real builder with every Deriv root block in place', () => {
        loadFixture('turbo-r100-over2-over4');
        const tops = workspace.getTopBlocks(false).map(b => b.type).sort();
        expect(tops).toEqual(['after_purchase', 'before_purchase', 'procedures_defnoreturn', 'trade_definition']);
        const market = workspace.getBlocksByType('trade_definition_market', false)[0];
        expect(market.getFieldValue('SYMBOL_LIST')).toBe('R_100');
        expect(market.getFieldValue('MARKET_LIST')).toBe('synthetic_index');
        expect(market.getFieldValue('SUBMARKET_LIST')).toBe('random_index');
        expect(workspace.getBlocksByType('trade_definition_tradetype', false)[0].getFieldValue('TRADETYPE_LIST')).toBe('overunder');
        expect(workspace.getBlocksByType('trade_definition_contracttype', false)[0].getFieldValue('TYPE_LIST')).toBe('both');
        const options = workspace.getBlocksByType('trade_definition_tradeoptions', false)[0];
        expect(options.getFieldValue('DURATIONTYPE_LIST')).toBe('t');
        expect(options.getInput('PREDICTION')).toBeTruthy();
        expect(options.getInputTargetBlock('PREDICTION').type).toBe('variables_get');
        expect(options.getInputTargetBlock('AMOUNT').type).toBe('variables_get');
        // Every call resolved to the single recovery-stake procedure (no auto-created duplicates).
        expect(workspace.getBlocksByType('procedures_defnoreturn', false)).toHaveLength(1);
        expect(workspace.getBlocksByType('procedures_callnoreturn', false).length).toBeGreaterThanOrEqual(2);
    });

    it('generates runnable code that arms once, trades the lock and recovers like the Turbo engine', () => {
        loadFixture('turbo-r100-over2-over4');
        const code = buildRunner(workspace);
        expect(code).toContain("symbol              : 'R_100'");
        expect(code).toContain('"DIGITOVER","DIGITUNDER"');

        // Arming: first 3 evaluations see a dead tape (Over 2 never hits), then a healthy one.
        const market = fakeMarket({
            results: ['W', 'L', 'L', 'W', 'W'],
            digits: state => (state.beforeEvaluations <= 3 ? BAD_DIGITS : GOOD_DIGITS),
        });
        expect(runStrategy(code, market)).toBe('exhausted');

        expect(market.state.init.symbol).toBe('R_100');
        expect(market.state.tradeOptions.duration).toBe(1);
        expect(market.state.tradeOptions.duration_unit).toBe('t');
        expect(market.state.beforeEvaluations).toBeGreaterThan(3); // waited, then armed
        expect(market.state.notifications.some(m => /Armed on Volatility 100 Index/.test(m))).toBe(true);

        const trades = market.state.trades.map(t => [t.type, t.prediction, t.stake, t.won ? 'W' : 'L']);
        expect(trades).toEqual([
            ['DIGITOVER', 2, 1, 'W'], // normal leg at base stake
            ['DIGITOVER', 2, 1, 'L'], // loss → debt 1.00
            ['DIGITOVER', 4, 1.16, 'L'], // recovery: ceil₂(1.00 × 1.1 / 0.95) = 1.16 → debt 2.16
            ['DIGITOVER', 4, 2.51, 'W'], // recovery: ceil₂(2.16 × 1.1 / 0.95) = 2.51 → +2.38 clears debt
            ['DIGITOVER', 2, 1, 'W'], // straight back to the normal leg at base stake
        ]);
        expect(market.state.notifications.some(m => /Recovery step 1 — Over 4 at 1.16 USD to clear 1 USD/.test(m))).toBe(true);
        expect(market.state.notifications.some(m => /Recovery step 2 — Over 4 at 2.51 USD to clear 2.16 USD/.test(m))).toBe(true);
        expect(market.state.notifications.some(m => /Recovery complete — debt cleared/.test(m))).toBe(true);
    });

    it('stops at stop-loss on a losing ladder and never trades past it', () => {
        loadFixture('turbo-r100-over2-over4');
        const code = buildRunner(workspace);
        const market = fakeMarket({ results: ['L', 'L', 'L', 'L', 'L', 'L', 'L', 'L'] });
        expect(runStrategy(code, market)).toBe('stopped');
        const stakes = market.state.trades.map(t => t.stake);
        // 1.00 → 1.16 → 2.51 → ceil₂(4.67 × 1.1 / 0.95) = 5.41 ; total −10.08 ≤ −5 → SL halt
        expect(stakes).toEqual([1, 1.16, 2.51, 5.41]);
        expect(market.state.trades.map(t => t.prediction)).toEqual([2, 4, 4, 4]);
        expect(market.state.totalProfit).toBeLessThanOrEqual(-5);
        expect(market.state.notifications.some(m => /Stop loss 5.00 USD hit/.test(m))).toBe(true);
    });

    it('stops at take-profit', () => {
        loadFixture('turbo-r100-over2-over4');
        const code = buildRunner(workspace);
        const market = fakeMarket({ results: Array.from({ length: 40 }, () => 'W') });
        expect(runStrategy(code, market)).toBe('stopped');
        // 0.40 per win → 25 wins reach the 10.00 take-profit.
        expect(market.state.trades).toHaveLength(25);
        expect(market.state.totalProfit).toBeGreaterThanOrEqual(10);
        expect(market.state.notifications.some(m => /Take profit 10.00 USD reached/.test(m))).toBe(true);
    });

    it('trips the circuit breaker after the modelled loss depth (Under lock, wide TP/SL)', () => {
        loadFixture('turbo-1hz100v-under7-under5-wide');
        const code = buildRunner(workspace);
        expect(code).toContain("symbol              : '1HZ100V'");
        const market = fakeMarket({ results: Array.from({ length: 12 }, () => 'L') });
        expect(runStrategy(code, market)).toBe('stopped');
        // breakerDepth 5 → exactly 5 consecutive losses, then halt.
        expect(market.state.trades).toHaveLength(5);
        expect(market.state.trades.map(t => [t.type, t.prediction])).toEqual([
            ['DIGITUNDER', 7],
            ['DIGITUNDER', 5],
            ['DIGITUNDER', 5],
            ['DIGITUNDER', 5],
            ['DIGITUNDER', 5],
        ]);
        expect(market.state.notifications.some(m => /Circuit breaker: 5 consecutive losses/.test(m))).toBe(true);
    });

    it('keeps recovery open on a partial win and clears it on the next', () => {
        loadFixture('turbo-1hz100v-under7-under5-wide');
        const code = buildRunner(workspace);
        // Stake 0.50: L (debt 0.50) → recovery ceil₂(0.55/0.95)=0.58 L (debt 1.08) → ceil₂(1.188/0.95)=1.26 ...
        // Force a partial: cap balance so the recovery stake is clipped below what clears the debt.
        const market = fakeMarket({ results: ['L', 'L', 'W', 'W', 'W'], balance: 1.7 });
        expect(runStrategy(code, market)).toBe('exhausted');
        const t = market.state.trades;
        expect(t[0]).toMatchObject({ type: 'DIGITUNDER', prediction: 7, stake: 0.5, won: false });
        expect(t[1]).toMatchObject({ type: 'DIGITUNDER', prediction: 5, stake: 0.58, won: false });
        // Debt 1.08 wants 1.26 but balance is 1.70 − 0.50 − 0.58 = 0.62 → stake clipped to 0.62.
        expect(t[2]).toMatchObject({ type: 'DIGITUNDER', prediction: 5, stake: 0.62, won: true });
        // Win pays 0.62 × 0.95 = 0.59 → debt 0.49 remains → still recovery, resized: ceil₂(0.49 × 1.1 / 0.95) = 0.57
        expect(t[3]).toMatchObject({ type: 'DIGITUNDER', prediction: 5, stake: 0.57, won: true });
        // Debt cleared → back to Under 7 at base 0.50.
        expect(t[4]).toMatchObject({ type: 'DIGITUNDER', prediction: 7, stake: 0.5 });
        expect(market.state.notifications.some(m => /Partial recovery/.test(m))).toBe(true);
    });
});
